/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Sebastian
 */
public class ComprarTicket extends javax.swing.JFrame {

    /**
     * Creates new form ComprarTicket
     */
    public ComprarTicket() {
        initComponents();
        imgSectores();
   
    }
    
    public void imgSectores(){
        ImageIcon estadio = new ImageIcon(getClass().getResource("/Imagenes/sectores.png"));
        Icon estadioIcono =   new ImageIcon(estadio.getImage().getScaledInstance(this.jlblImagen.getWidth(), this.jlblImagen.getHeight(), Image.SCALE_SMOOTH));
        this.jlblImagen.setIcon(estadioIcono);
    }
    
    public void imgRapanui(){
        ImageIcon estadio = new ImageIcon(getClass().getResource("/Imagenes/sector_rapanui.png"));
        Icon estadioIcono =   new ImageIcon(estadio.getImage().getScaledInstance(this.jlblImagen.getWidth(), this.jlblImagen.getHeight(), Image.SCALE_SMOOTH));
        this.jlblImagen.setIcon(estadioIcono);  
    }
    
    public void imgOceano(){
        ImageIcon estadio = new ImageIcon(getClass().getResource("/Imagenes/sector_oceano.png"));
        Icon estadioIcono =   new ImageIcon(estadio.getImage().getScaledInstance(this.jlblImagen.getWidth(), this.jlblImagen.getHeight(), Image.SCALE_SMOOTH));
        this.jlblImagen.setIcon(estadioIcono);  
    }
    
    public void imgCordillera(){
        ImageIcon estadio = new ImageIcon(getClass().getResource("/Imagenes/sector_cordillera.png"));
        Icon estadioIcono =   new ImageIcon(estadio.getImage().getScaledInstance(this.jlblImagen.getWidth(), this.jlblImagen.getHeight(), Image.SCALE_SMOOTH));
        this.jlblImagen.setIcon(estadioIcono);  
    }
    
    public void imgLautaro(){
        ImageIcon estadio = new ImageIcon(getClass().getResource("/Imagenes/sector_lautaro.png"));
        Icon estadioIcono =   new ImageIcon(estadio.getImage().getScaledInstance(this.jlblImagen.getWidth(), this.jlblImagen.getHeight(), Image.SCALE_SMOOTH));
        this.jlblImagen.setIcon(estadioIcono);  
    }
    
    public void imgCaupolican(){
        ImageIcon estadio = new ImageIcon(getClass().getResource("/Imagenes/sector_caupolican.png"));
        Icon estadioIcono =   new ImageIcon(estadio.getImage().getScaledInstance(this.jlblImagen.getWidth(), this.jlblImagen.getHeight(), Image.SCALE_SMOOTH));
        this.jlblImagen.setIcon(estadioIcono);  
    }
    
    public void imgGalvarino(){
        ImageIcon estadio = new ImageIcon(getClass().getResource("/Imagenes/sector_galvarino.png"));
        Icon estadioIcono =   new ImageIcon(estadio.getImage().getScaledInstance(this.jlblImagen.getWidth(), this.jlblImagen.getHeight(), Image.SCALE_SMOOTH));
        this.jlblImagen.setIcon(estadioIcono);  
    }
    
    public void imgTucalpel(){
        ImageIcon estadio = new ImageIcon(getClass().getResource("/Imagenes/sector_tucapel.png"));
        Icon estadioIcono =   new ImageIcon(estadio.getImage().getScaledInstance(this.jlblImagen.getWidth(), this.jlblImagen.getHeight(), Image.SCALE_SMOOTH));
        this.jlblImagen.setIcon(estadioIcono);  
    }
    
    public void imgArica(){
        ImageIcon estadio = new ImageIcon(getClass().getResource("/Imagenes/sector_arica.png"));
        Icon estadioIcono =   new ImageIcon(estadio.getImage().getScaledInstance(this.jlblImagen.getWidth(), this.jlblImagen.getHeight(), Image.SCALE_SMOOTH));
        this.jlblImagen.setIcon(estadioIcono);  
    }
    
    public void imgMagallanes(){
        ImageIcon estadio = new ImageIcon(getClass().getResource("/Imagenes/sector_magallanes.png"));
        Icon estadioIcono =   new ImageIcon(estadio.getImage().getScaledInstance(this.jlblImagen.getWidth(), this.jlblImagen.getHeight(), Image.SCALE_SMOOTH));
        this.jlblImagen.setIcon(estadioIcono);  
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jlblImagen = new javax.swing.JLabel();
        jrbtCordillera = new javax.swing.JRadioButton();
        jrbtOceano = new javax.swing.JRadioButton();
        jrbtCaupolican = new javax.swing.JRadioButton();
        jrbtGalvarino = new javax.swing.JRadioButton();
        jrbtLautaro = new javax.swing.JRadioButton();
        jrbtTucapel = new javax.swing.JRadioButton();
        jrbtArica = new javax.swing.JRadioButton();
        jrbtMagallanes = new javax.swing.JRadioButton();
        jrbtRapanui = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Venta de Ticket");

        buttonGroup1.add(jrbtCordillera);
        jrbtCordillera.setText("Cordillera");
        jrbtCordillera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtCordilleraActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbtOceano);
        jrbtOceano.setText("Oceano");
        jrbtOceano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtOceanoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbtCaupolican);
        jrbtCaupolican.setText("Caupolican");
        jrbtCaupolican.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtCaupolicanActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbtGalvarino);
        jrbtGalvarino.setText("Galvarino");
        jrbtGalvarino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtGalvarinoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbtLautaro);
        jrbtLautaro.setText("Lautaro");
        jrbtLautaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtLautaroActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbtTucapel);
        jrbtTucapel.setText("Tucapel");
        jrbtTucapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtTucapelActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbtArica);
        jrbtArica.setText("Arica");
        jrbtArica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtAricaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbtMagallanes);
        jrbtMagallanes.setText("Magallanes");
        jrbtMagallanes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtMagallanesActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbtRapanui);
        jrbtRapanui.setText("Rapa Nui");
        jrbtRapanui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtRapanuiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Estadio Monumental - David Arellano");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbtRapanui)
                    .addComponent(jrbtCaupolican)
                    .addComponent(jrbtOceano)
                    .addComponent(jrbtCordillera)
                    .addComponent(jrbtGalvarino)
                    .addComponent(jrbtLautaro)
                    .addComponent(jrbtTucapel)
                    .addComponent(jrbtArica)
                    .addComponent(jrbtMagallanes))
                .addGap(130, 130, 130))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbtRapanui)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbtOceano)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jlblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrbtCordillera)
                        .addGap(6, 6, 6)
                        .addComponent(jrbtCaupolican)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrbtGalvarino)
                        .addGap(3, 3, 3)
                        .addComponent(jrbtLautaro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrbtTucapel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrbtArica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrbtMagallanes)))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbtCordilleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtCordilleraActionPerformed
        imgCordillera();
    }//GEN-LAST:event_jrbtCordilleraActionPerformed

    private void jrbtOceanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtOceanoActionPerformed
        imgOceano();
    }//GEN-LAST:event_jrbtOceanoActionPerformed

    private void jrbtCaupolicanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtCaupolicanActionPerformed
        imgCaupolican();
    }//GEN-LAST:event_jrbtCaupolicanActionPerformed

    private void jrbtGalvarinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtGalvarinoActionPerformed
        imgGalvarino();
    }//GEN-LAST:event_jrbtGalvarinoActionPerformed

    private void jrbtLautaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtLautaroActionPerformed
        imgLautaro();
    }//GEN-LAST:event_jrbtLautaroActionPerformed

    private void jrbtRapanuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtRapanuiActionPerformed
        imgRapanui();
    }//GEN-LAST:event_jrbtRapanuiActionPerformed

    private void jrbtTucapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtTucapelActionPerformed
        imgTucalpel();
    }//GEN-LAST:event_jrbtTucapelActionPerformed

    private void jrbtAricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtAricaActionPerformed
        imgArica();
    }//GEN-LAST:event_jrbtAricaActionPerformed

    private void jrbtMagallanesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtMagallanesActionPerformed
        imgMagallanes();
    }//GEN-LAST:event_jrbtMagallanesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComprarTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComprarTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComprarTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComprarTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComprarTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlblImagen;
    private javax.swing.JRadioButton jrbtArica;
    private javax.swing.JRadioButton jrbtCaupolican;
    private javax.swing.JRadioButton jrbtCordillera;
    private javax.swing.JRadioButton jrbtGalvarino;
    private javax.swing.JRadioButton jrbtLautaro;
    private javax.swing.JRadioButton jrbtMagallanes;
    private javax.swing.JRadioButton jrbtOceano;
    private javax.swing.JRadioButton jrbtRapanui;
    private javax.swing.JRadioButton jrbtTucapel;
    // End of variables declaration//GEN-END:variables
}
