/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.RegistroCategoria;
import controlador.RegistroCliente;
import controlador.RegistroEquipo;
import controlador.RegistroEstadio;
import controlador.RegistroEvento;
import controlador.RegistroUbicacion;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Categoria;
import modelo.Cliente;
import modelo.Equipo;
import modelo.Estadio;
import modelo.Evento;
import modelo.Ticket;
import modelo.UbicacionEstadio;


/**
 *
 * @author Sebastian
 */
public class ComprarTicket extends javax.swing.JFrame {

    //creo una variable de Evento para guardar los datos provenientes desde la otra ventana
    private final Evento evento;
    private int idEvento;
    private int idEstadio, idSector;
    private String rutCliente, nomEstadio;

    ;

    /**
     * Creates new form ComprarTicket
     */
    //public ComprarTicket() {
    public ComprarTicket(final Evento evento) {
        initComponents();
        imgSectores();
        this.evento = evento;
        idEvento = evento.getIdEvento();
        consultarEstadio(1);
        consultarEvento();
    }

    public void imgSectores() {
        ImageIcon estadio = new ImageIcon(getClass().getResource("/Imagenes/sectores.png"));
        Icon estadioIcono = new ImageIcon(estadio.getImage().getScaledInstance(this.jlblImagen.getWidth(), this.jlblImagen.getHeight(), Image.SCALE_SMOOTH));
        this.jlblImagen.setIcon(estadioIcono);
    }

    public void imgRapanui() {
        ImageIcon estadio = new ImageIcon(getClass().getResource("/Imagenes/sector_rapanui.png"));
        Icon estadioIcono = new ImageIcon(estadio.getImage().getScaledInstance(this.jlblImagen.getWidth(), this.jlblImagen.getHeight(), Image.SCALE_SMOOTH));
        this.jlblImagen.setIcon(estadioIcono);
    }

    public void imgOceano() {
        ImageIcon estadio = new ImageIcon(getClass().getResource("/Imagenes/sector_oceano.png"));
        Icon estadioIcono = new ImageIcon(estadio.getImage().getScaledInstance(this.jlblImagen.getWidth(), this.jlblImagen.getHeight(), Image.SCALE_SMOOTH));
        this.jlblImagen.setIcon(estadioIcono);
    }

    public void imgCordillera() {
        ImageIcon estadio = new ImageIcon(getClass().getResource("/Imagenes/sector_cordillera.png"));
        Icon estadioIcono = new ImageIcon(estadio.getImage().getScaledInstance(this.jlblImagen.getWidth(), this.jlblImagen.getHeight(), Image.SCALE_SMOOTH));
        this.jlblImagen.setIcon(estadioIcono);
    }

    public void imgLautaro() {
        ImageIcon estadio = new ImageIcon(getClass().getResource("/Imagenes/sector_lautaro.png"));
        Icon estadioIcono = new ImageIcon(estadio.getImage().getScaledInstance(this.jlblImagen.getWidth(), this.jlblImagen.getHeight(), Image.SCALE_SMOOTH));
        this.jlblImagen.setIcon(estadioIcono);
    }

    public void imgCaupolican() {
        ImageIcon estadio = new ImageIcon(getClass().getResource("/Imagenes/sector_caupolican.png"));
        Icon estadioIcono = new ImageIcon(estadio.getImage().getScaledInstance(this.jlblImagen.getWidth(), this.jlblImagen.getHeight(), Image.SCALE_SMOOTH));
        this.jlblImagen.setIcon(estadioIcono);
    }

    public void imgGalvarino() {
        ImageIcon estadio = new ImageIcon(getClass().getResource("/Imagenes/sector_galvarino.png"));
        Icon estadioIcono = new ImageIcon(estadio.getImage().getScaledInstance(this.jlblImagen.getWidth(), this.jlblImagen.getHeight(), Image.SCALE_SMOOTH));
        this.jlblImagen.setIcon(estadioIcono);
    }

    public void imgTucalpel() {
        ImageIcon estadio = new ImageIcon(getClass().getResource("/Imagenes/sector_tucapel.png"));
        Icon estadioIcono = new ImageIcon(estadio.getImage().getScaledInstance(this.jlblImagen.getWidth(), this.jlblImagen.getHeight(), Image.SCALE_SMOOTH));
        this.jlblImagen.setIcon(estadioIcono);
    }

    public void imgArica() {
        ImageIcon estadio = new ImageIcon(getClass().getResource("/Imagenes/sector_arica.png"));
        Icon estadioIcono = new ImageIcon(estadio.getImage().getScaledInstance(this.jlblImagen.getWidth(), this.jlblImagen.getHeight(), Image.SCALE_SMOOTH));
        this.jlblImagen.setIcon(estadioIcono);
    }

    public void imgMagallanes() {
        ImageIcon estadio = new ImageIcon(getClass().getResource("/Imagenes/sector_magallanes.png"));
        Icon estadioIcono = new ImageIcon(estadio.getImage().getScaledInstance(this.jlblImagen.getWidth(), this.jlblImagen.getHeight(), Image.SCALE_SMOOTH));
        this.jlblImagen.setIcon(estadioIcono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        jlblImagen = new javax.swing.JLabel();
        jlblestadio = new javax.swing.JLabel();
        jrbtRapanui = new javax.swing.JRadioButton();
        jrbtCordillera = new javax.swing.JRadioButton();
        jrbtOceano = new javax.swing.JRadioButton();
        jrbtCaupolican = new javax.swing.JRadioButton();
        jrbtGalvarino = new javax.swing.JRadioButton();
        jrbtLautaro = new javax.swing.JRadioButton();
        jrbtTucapel = new javax.swing.JRadioButton();
        jrbtArica = new javax.swing.JRadioButton();
        jrbtMagallanes = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jlblPrecioOceano = new javax.swing.JLabel();
        jlblPrecioRapanui = new javax.swing.JLabel();
        jlblPrecioCordillera = new javax.swing.JLabel();
        jlblPrecioCaupolican = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlblPrecioGalvarino = new javax.swing.JLabel();
        jlblPrecioLautaro = new javax.swing.JLabel();
        jlblPrecioTucapel = new javax.swing.JLabel();
        jlblPrecioArica = new javax.swing.JLabel();
        jlblPrecioMagallanes = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlblLocalVisita = new javax.swing.JLabel();
        jlblDescripcion = new javax.swing.JLabel();
        jlblFechaHora = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtxtRun = new javax.swing.JTextField();
        jbtnBuscar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtxtNombre = new javax.swing.JTextField();
        jtxtApellidos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtxtCategoria = new javax.swing.JTextField();
        jbtnComprar = new javax.swing.JButton();
        jbtnLimpiar = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();

        jLabel6.setForeground(new java.awt.Color(153, 255, 255));
        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Venta de Ticket");
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        jlblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jlblestadio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblestadio.setText("Estadio Monumental - David Arellano");
        jlblestadio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        buttonGroup1.add(jrbtRapanui);
        jrbtRapanui.setText("Rapa Nui");
        jrbtRapanui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtRapanuiActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbtCordillera);
        jrbtCordillera.setText("Cordillera");
        jrbtCordillera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtCordilleraActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbtOceano);
        jrbtOceano.setText("Oceano");
        jrbtOceano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtOceanoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbtCaupolican);
        jrbtCaupolican.setText("Caupolican");
        jrbtCaupolican.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtCaupolicanActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbtGalvarino);
        jrbtGalvarino.setText("Galvarino");
        jrbtGalvarino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtGalvarinoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbtLautaro);
        jrbtLautaro.setText("Lautaro");
        jrbtLautaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtLautaroActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbtTucapel);
        jrbtTucapel.setText("Tucapel");
        jrbtTucapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtTucapelActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbtArica);
        jrbtArica.setText("Arica");
        jrbtArica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtAricaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbtMagallanes);
        jrbtMagallanes.setText("Magallanes");
        jrbtMagallanes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtMagallanesActionPerformed(evt);
            }
        });

        jLabel2.setText("SECTORES");

        jlblPrecioOceano.setText("$ 30.000");

        jlblPrecioRapanui.setText("$ 45.000");

        jlblPrecioCordillera.setText("$ 20.000");

        jlblPrecioCaupolican.setText("$ 10.000");

        jLabel7.setText("PRECIOS");

        jlblPrecioGalvarino.setText("$ 10.000");

        jlblPrecioLautaro.setText("$ 10.000");

        jlblPrecioTucapel.setText("$ 10.000");

        jlblPrecioArica.setText("$   8.000");

        jlblPrecioMagallanes.setText("$   8.000");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoColoColo.png"))); // NOI18N

        jlblLocalVisita.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jlblLocalVisita.setText("jLabel10");

        jlblDescripcion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlblDescripcion.setText("jLabel11");

        jlblFechaHora.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlblFechaHora.setText("jLabel12");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Comprador"));

        jLabel4.setText("RUN");

        jbtnBuscar.setBackground(new java.awt.Color(0, 102, 255));
        jbtnBuscar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jbtnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnBuscar.setText("Buscar");
        jbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarActionPerformed(evt);
            }
        });

        jLabel5.setText("NOMBRE");

        jLabel8.setText("APELLIDOS");

        jtxtNombre.setEnabled(false);

        jtxtApellidos.setEnabled(false);

        jLabel9.setText("CATEGORIA CLIENTE");

        jtxtCategoria.setEnabled(false);

        jbtnComprar.setBackground(new java.awt.Color(0, 102, 0));
        jbtnComprar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jbtnComprar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnComprar.setText("Vender");
        jbtnComprar.setEnabled(false);
        jbtnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnComprarActionPerformed(evt);
            }
        });

        jbtnLimpiar.setText("Limpiar");

        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtxtRun, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jbtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtxtCategoria, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jtxtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(233, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtRun, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jbtnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnComprar, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblLocalVisita)
                    .addComponent(jlblDescripcion)
                    .addComponent(jlblFechaHora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jlblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jrbtRapanui, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(47, 47, 47)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jlblPrecioRapanui, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jrbtOceano, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jlblPrecioOceano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jrbtMagallanes, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jlblPrecioMagallanes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jrbtArica, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jlblPrecioArica, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jrbtCordillera, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jlblPrecioCordillera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jrbtCaupolican, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jlblPrecioCaupolican, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jrbtGalvarino, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jlblPrecioGalvarino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jrbtLautaro, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jlblPrecioLautaro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jrbtTucapel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jlblPrecioTucapel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(93, 93, 93))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jlblestadio)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jlblLocalVisita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblDescripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblFechaHora)
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrbtRapanui)
                            .addComponent(jlblPrecioRapanui, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrbtOceano)
                            .addComponent(jlblPrecioOceano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrbtCordillera)
                            .addComponent(jlblPrecioCordillera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrbtCaupolican)
                            .addComponent(jlblPrecioCaupolican, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrbtGalvarino)
                            .addComponent(jlblPrecioGalvarino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrbtLautaro)
                            .addComponent(jlblPrecioLautaro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrbtTucapel)
                            .addComponent(jlblPrecioTucapel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblPrecioArica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jrbtArica))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrbtMagallanes)
                            .addComponent(jlblPrecioMagallanes))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addGap(5, 5, 5)
                        .addComponent(jlblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblestadio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jrbtCordilleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtCordilleraActionPerformed
        imgCordillera();
    }//GEN-LAST:event_jrbtCordilleraActionPerformed

    private void jrbtOceanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtOceanoActionPerformed
        imgOceano();
    }//GEN-LAST:event_jrbtOceanoActionPerformed

    private void jrbtCaupolicanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtCaupolicanActionPerformed
        imgCaupolican();
    }//GEN-LAST:event_jrbtCaupolicanActionPerformed

    private void jrbtGalvarinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtGalvarinoActionPerformed
        imgGalvarino();
    }//GEN-LAST:event_jrbtGalvarinoActionPerformed

    private void jrbtLautaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtLautaroActionPerformed
        imgLautaro();
    }//GEN-LAST:event_jrbtLautaroActionPerformed

    private void jrbtRapanuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtRapanuiActionPerformed
        imgRapanui();
    }//GEN-LAST:event_jrbtRapanuiActionPerformed

    private void jrbtTucapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtTucapelActionPerformed
        imgTucalpel();
    }//GEN-LAST:event_jrbtTucapelActionPerformed

    private void jrbtAricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtAricaActionPerformed
        imgArica();
    }//GEN-LAST:event_jrbtAricaActionPerformed

    private void jrbtMagallanesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtMagallanesActionPerformed
        imgMagallanes();
    }//GEN-LAST:event_jrbtMagallanesActionPerformed

    private void jbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarActionPerformed

        limpiar();

        if (this.jrbtArica.isSelected() || this.jrbtMagallanes.isSelected() || this.jrbtCaupolican.isSelected()
                || this.jrbtTucapel.isSelected() || this.jrbtLautaro.isSelected() || this.jrbtGalvarino.isSelected()
                || this.jrbtCordillera.isSelected() || this.jrbtOceano.isSelected() || this.jrbtRapanui.isSelected()) {
            if (consultarCliente(this.jtxtRun.getText())) {
                habilitar();
                noEditar();
                rutCliente = this.jtxtRun.getText();
                this.jbtnComprar.setEnabled(true);
                
            } else if (this.jtxtRun.getText().isBlank()) {
                JOptionPane.showMessageDialog(null, "Debe ingresar un RUN", "Run Vacío", 0);
                this.jtxtRun.requestFocus();

            } else {
                JOptionPane.showMessageDialog(null, "No existe el RUN " + this.jtxtRun.getText(), "Error al buscar RUN", 0);
                this.jtxtRun.requestFocus();
                limpiar();
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un sector del Estadio", "Error de Seleccion de Sector", 1);
        }
    }//GEN-LAST:event_jbtnBuscarActionPerformed

    private void jbtnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnComprarActionPerformed
        int sector = 0, precio = 0;

        int resp = JOptionPane.showConfirmDialog(this, "¿Desea confirmar la compra?", "COnfirmación de Compra", JOptionPane.YES_NO_OPTION, 0);
        if (resp == 0) {
            if (this.jrbtRapanui.isSelected()) {
                sector = 1;
                precio = 45000;
            } else if (this.jrbtOceano.isSelected()) {
                sector = 2;
                precio = 30000;
            } else if (this.jrbtCordillera.isSelected()) {
                sector = 3;
                precio = 20000;
            } else if (this.jrbtCaupolican.isSelected()) {
                sector = 4;
                precio = 10000;
            } else if (this.jrbtGalvarino.isSelected()) {
                sector = 5;
                precio = 10000;
            } else if (this.jrbtLautaro.isSelected()) {
                sector = 6;
                precio = 10000;
            } else if (this.jrbtTucapel.isSelected()) {
                sector = 7;
                precio = 10000;
            } else if (this.jrbtArica.isSelected()) {
                sector = 8;
                precio = 8000;
            } else {
                sector = 9;
                precio = 8000;
            }

            //Ticket ticket = new Ticket(0, precio, rutCliente, 1, sector, idEvento);
            Ticket ticket = new Ticket(0, precio, rutCliente, null, 1, sector, idEvento);
            PagarTicket window = new PagarTicket(ticket);
            window.setVisible(true);
            this.dispose();
            //RegistroVenta regven = RegistroVenta();
            
//            if (regven.agregar(venta)) {
//                JOptionPane.showMessageDialog(this, "Se agregó el Cliente", "Aviso", 1);
//                limpiar();
//            } else {
//                JOptionPane.showMessageDialog(this, "No se agregó el cliente", "Aviso", 1);
//            }

            //VentaTicket window = VentaTicket(venta);
//            VentaTicket window = VentaTicket(venta);
//            
            //
        }
    }//GEN-LAST:event_jbtnComprarActionPerformed

    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtnCancelarActionPerformed

    private String consultarEquipo(int idVisita) {
        String equipoVisita;
        RegistroEquipo re = new RegistroEquipo();
        Equipo equipo = re.buscarPorId(idVisita);
        equipoVisita = equipo.getNombreEquipo();

        return equipoVisita;
    }

    private String consultarUbicacion(int idUbicacion) {
        String nomUbic;

        RegistroUbicacion rc = new RegistroUbicacion();
        UbicacionEstadio ubicacion = rc.buscarPorId(idUbicacion);
        nomUbic = ubicacion.getNombreUbicacion();

        return nomUbic;
    }

    private void consultarEstadio(int idEst) {

        RegistroEstadio res = new RegistroEstadio();
        Estadio estadio = res.buscarPorId(idEst);
        idEstadio = estadio.getIdEstadio();
        nomEstadio = estadio.getNombreEstadio();

        System.out.println(nomEstadio);
        this.jlblestadio.setText(nomEstadio);
    }

    private String consultarCategoria(int idCategoria) {
        String nomCategoria;

        RegistroCategoria rc = new RegistroCategoria();
        Categoria categoria = rc.buscarPorId(idCategoria);
        nomCategoria = categoria.getNombreCategoria();

        return nomCategoria;
    }

    private boolean consultarCliente(String run) {
        String equipoVisita, runcli;
        RegistroCliente rc = new RegistroCliente();
        Cliente cliente = rc.buscarPorRut(run);

        runcli = cliente.getRutCliente();
        System.out.println(runcli);
        if (runcli != null) {
            this.jtxtNombre.setText(cliente.getNombre());
            this.jtxtApellidos.setText(cliente.getAppaterno() + " " + cliente.getApmaterno());
            this.jtxtCategoria.setText(consultarCategoria(cliente.getCategoria()));
            return true;
        } else {
            return false;
        }

    }

    public void consultarEvento() {
        RegistroEvento regev = new RegistroEvento();
        Evento evento = regev.buscarPorId(idEvento);

        this.jlblLocalVisita.setText(evento.getEquipoLocal() + " vs " + consultarEquipo(evento.getVisita()));
        this.jlblDescripcion.setText(evento.getDescripcionEvento() + " | Jornada: " + evento.getJornadaEvento());
        this.jlblFechaHora.setText(evento.getFechaEvento() + " | " + evento.getHoraEvento() + " hrs");

    }

    public void limpiar() {
        this.jtxtNombre.setText("");
        this.jtxtApellidos.setText("");
        this.jtxtCategoria.setText("");
    }

    public void noEditar() {
        this.jtxtNombre.setEditable(false);
        this.jtxtApellidos.setEditable(false);
        this.jtxtCategoria.setEditable(false);
    }

    public void habilitar() {
        this.jtxtNombre.setEnabled(true);
        this.jtxtApellidos.setEnabled(true);
        this.jtxtCategoria.setEnabled(true);
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ComprarTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ComprarTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ComprarTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ComprarTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ComprarTicket().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnBuscar;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JButton jbtnComprar;
    private javax.swing.JButton jbtnLimpiar;
    private javax.swing.JLabel jlblDescripcion;
    private javax.swing.JLabel jlblFechaHora;
    private javax.swing.JLabel jlblImagen;
    private javax.swing.JLabel jlblLocalVisita;
    private javax.swing.JLabel jlblPrecioArica;
    private javax.swing.JLabel jlblPrecioCaupolican;
    private javax.swing.JLabel jlblPrecioCordillera;
    private javax.swing.JLabel jlblPrecioGalvarino;
    private javax.swing.JLabel jlblPrecioLautaro;
    private javax.swing.JLabel jlblPrecioMagallanes;
    private javax.swing.JLabel jlblPrecioOceano;
    private javax.swing.JLabel jlblPrecioRapanui;
    private javax.swing.JLabel jlblPrecioTucapel;
    private javax.swing.JLabel jlblestadio;
    private javax.swing.JRadioButton jrbtArica;
    private javax.swing.JRadioButton jrbtCaupolican;
    private javax.swing.JRadioButton jrbtCordillera;
    private javax.swing.JRadioButton jrbtGalvarino;
    private javax.swing.JRadioButton jrbtLautaro;
    private javax.swing.JRadioButton jrbtMagallanes;
    private javax.swing.JRadioButton jrbtOceano;
    private javax.swing.JRadioButton jrbtRapanui;
    private javax.swing.JRadioButton jrbtTucapel;
    private javax.swing.JTextField jtxtApellidos;
    private javax.swing.JTextField jtxtCategoria;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JTextField jtxtRun;
    // End of variables declaration//GEN-END:variables

    
}
