/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.RegistroEquipo;
import controlador.RegistroEvento;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.Equipo;
import modelo.Evento;

/**
 *
 * @author Sebastian
 */
public class ListarEvento extends javax.swing.JFrame {

    private int idEvento, jornada, idVisita;
    private String equipoLocal, descripcionEvento, horaEvento, nomVisita;
    private Date fechaEvento;
    private boolean disponible;

    /**
     * Creates new form ListarEvento
     */
    public ListarEvento() {
        initComponents();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jlblJornada = new javax.swing.JLabel();
        jlblidEvento = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jbtnBuscar = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();
        jlblHora = new javax.swing.JLabel();
        jlblEvento = new javax.swing.JLabel();
        jlblDescripcion = new javax.swing.JLabel();
        jbtnLimpiar = new javax.swing.JButton();
        jlblFecha = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblListarEventos = new javax.swing.JTable();
        jbtnVender = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jlblJornada.setText("jLabel4");

        jlblidEvento.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listado de Eventos");
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoColoColo.png"))); // NOI18N

        jLabel2.setText("BUSCAR EVENTO");

        jbtnBuscar.setBackground(new java.awt.Color(0, 102, 255));
        jbtnBuscar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jbtnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnBuscar.setText("Buscar");
        jbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarActionPerformed(evt);
            }
        });

        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });

        jlblEvento.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jbtnLimpiar.setText("Limpiar");
        jbtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLimpiarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel6.setText("Listar Eventos Programados");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Eventos Programados"));

        jtblListarEventos.setBackground(new java.awt.Color(255, 255, 255));
        jtblListarEventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Visita", "Jornada", "Fecha", "Hora", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblListarEventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblListarEventosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblListarEventos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addContainerGap())
        );

        jbtnVender.setBackground(new java.awt.Color(0, 102, 255));
        jbtnVender.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jbtnVender.setForeground(new java.awt.Color(255, 255, 255));
        jbtnVender.setText("Vender Ticket");
        jbtnVender.setEnabled(false);
        jbtnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jlblDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                                .addComponent(jbtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnVender)
                                .addGap(38, 38, 38)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnVender, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarActionPerformed
        cargarTabla();
    }//GEN-LAST:event_jbtnBuscarActionPerformed

    private void jbtnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVenderActionPerformed
          int idEventoSeleccionado;
//          
          idEventoSeleccionado = Integer.parseInt(this.jlblidEvento.getText());
//        equipoLocal = this.jlblEvento.getText();
//        descripcionEvento = this.jlblDescripcion.getText();
//        jornada = Integer.parseInt(this.jlblJornada.getText());
//        SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy");
//        fechaEvento = null;
//        try {
//            fechaEvento = formato.parse(this.jlblFecha.getText());
//        } catch (ParseException e) {
//            System.out.println("Error en la fecha " + e.getMessage());
//        }
//
//        horaEvento = this.jlblHora.getText();
        //Creo un objeto evento para enviar los datos seleccionados para realizar una venta desde la ventana ComprarTicket
        //Evento evento = new Evento(idEvento, equipoLocal, descripcionEvento, fechaEvento, horaEvento, 0, true);
       Evento evento = new Evento(idEventoSeleccionado, "", "", 0, null, null, 0, true);
//
        //Creo el Objeto de la Vista y le paso el evento
        ComprarTicket window = new ComprarTicket(evento);
        window.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jbtnVenderActionPerformed

   private String consultarEquipo(int idVisita) {
        String equipoVisita;
        RegistroEquipo re = new RegistroEquipo();
        Equipo equipo = re.buscarPorId(idVisita);
        equipoVisita = equipo.getNombreEquipo();

        return equipoVisita;
    }

    private void jtblListarEventosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblListarEventosMouseClicked
        int jorEve;
        //creo una variable para asignar el valor de la fila que estoy haciendo click
        int seleccionar = this.jtblListarEventos.rowAtPoint(evt.getPoint());

        //lleno los lbl con los datos obtenidos de cada columna de la fila
        //idEvento = Integer.parseInt(String.valueOf(this.jtblListarEventos.getValueAt(seleccionar, 0)));
        this.jlblidEvento.setText(String.valueOf(this.jtblListarEventos.getValueAt(seleccionar, 0)));
        this.jlblEvento.setText(equipoLocal + " vs " + String.valueOf(this.jtblListarEventos.getValueAt(seleccionar, 1)));
        jorEve = Integer.parseInt(String.valueOf(this.jtblListarEventos.getValueAt(seleccionar, 2)));
        this.jlblDescripcion.setText(descripcionEvento + " | JORNADA: "+ jorEve);
        this.jlblFecha.setText(String.valueOf(this.jtblListarEventos.getValueAt(seleccionar, 3)));
        this.jlblHora.setText(String.valueOf(this.jtblListarEventos.getValueAt(seleccionar, 4)));
        
        this.jbtnVender.setEnabled(true);
        
    }//GEN-LAST:event_jtblListarEventosMouseClicked

    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtnCancelarActionPerformed

    private void jbtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimpiarActionPerformed
        limpiar();
        idEvento = 0;
        cargarTabla();
        this.jbtnVender.setEnabled(false);
        this.jtxtBuscar.requestFocus();
    }//GEN-LAST:event_jbtnLimpiarActionPerformed

    public void cargarTabla() {
        RegistroEvento regev = new RegistroEvento();
        DefaultTableModel modelo = (DefaultTableModel) this.jtblListarEventos.getModel();

        try {
            idEvento = Integer.parseInt(this.jtxtBuscar.getText());
        } catch (NumberFormatException e) {
            idEvento = 0;
        }

        modelo.setRowCount(0);

        if (idEvento == 0) {//listar todos
            List<Evento> lista = regev.buscarTodos();

            for (Evento evento : lista) {
                idEvento = evento.getIdEvento();
                equipoLocal = evento.getEquipoLocal();
                descripcionEvento = evento.getDescripcionEvento();
                idVisita = evento.getVisita();
                
                nomVisita = this.consultarEquipo(idVisita);
                
                jornada = evento.getJornadaEvento();
                fechaEvento = evento.getFechaEvento();
                horaEvento = evento.getHoraEvento();
                disponible = evento.isDisponible();

                modelo.addRow(new Object[]{idEvento, nomVisita, jornada, fechaEvento, horaEvento, disponible});
            }
        } else { //listar por id

            Evento evento = regev.buscarPorId(idEvento);
            idEvento = evento.getIdEvento();
            equipoLocal = evento.getEquipoLocal();
            descripcionEvento = evento.getDescripcionEvento();
            idVisita = evento.getVisita();
            
            nomVisita = this.consultarEquipo(idVisita);
            
            jornada = evento.getJornadaEvento();
            fechaEvento = evento.getFechaEvento();
            horaEvento = evento.getHoraEvento();
            disponible = evento.isDisponible();

            modelo.addRow(new Object[]{idEvento, nomVisita, jornada, fechaEvento, horaEvento, disponible});
        }

    }

    public void limpiar() {
        this.jtxtBuscar.setText("");
        this.jlblEvento.setText("");
        this.jlblDescripcion.setText("");
        this.jlblFecha.setText("");
        this.jlblHora.setText("");
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ListarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ListarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ListarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ListarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ListarEvento().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnBuscar;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JButton jbtnLimpiar;
    private javax.swing.JButton jbtnVender;
    private javax.swing.JLabel jlblDescripcion;
    private javax.swing.JLabel jlblEvento;
    private javax.swing.JLabel jlblFecha;
    private javax.swing.JLabel jlblHora;
    private javax.swing.JLabel jlblJornada;
    private javax.swing.JLabel jlblidEvento;
    private javax.swing.JTable jtblListarEventos;
    private javax.swing.JTextField jtxtBuscar;
    // End of variables declaration//GEN-END:variables
}
