/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.RegistroCategoria;
import controlador.RegistroCliente;
import controlador.RegistroEquipo;
import controlador.RegistroEstadio;
import controlador.RegistroEvento;
import controlador.RegistroTicket;
import controlador.RegistroUbicacion;
import java.security.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import modelo.Categoria;
import modelo.Cliente;
import modelo.Equipo;
import modelo.Estadio;
import modelo.Evento;
import modelo.Ticket;
import modelo.UbicacionEstadio;

/**
 *
 * @author Sebastian
 */
public class PagarTicket extends javax.swing.JFrame {

    private Ticket ticket;
    private String runCliente;
    private int idEvento, idEstadio, idUbicacion, precioTicket, calculoPago, catCliente, totalPagar, efectivo;
    private Double descto;
    private boolean bandera;

    /**
     * Creates new form PagarTicket
     */
    public PagarTicket(final Ticket ticket) {
        initComponents();
        this.ticket = ticket;
        runCliente = ticket.getRutCliente();
        idEvento = ticket.getIdEvento();
        idEstadio = ticket.getIdEstadio();
        idUbicacion = ticket.getIdUbicacion();
        precioTicket = ticket.getPrecioTicket();
        ocultarPago();
        System.out.println(idUbicacion);
        informacionTicket();
        consultarEvento();
        consultarEstadio(idEstadio);
        consultarUbicacion(idUbicacion);
        descuentoCliente();
        totalPagar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void informacionTicket() {

        if (!consultarCliente(runCliente)) {
            System.out.println("Rut Invalido");
        }

        this.jlblRunCliente.setText(ticket.getRutCliente());
        runCliente = this.jlblRunCliente.getText();
        this.jlblPrecio.setText(String.valueOf(precioTicket));

    }

    private boolean consultarCliente(String run) {
        String equipoVisita, runcli;
        RegistroCliente rc = new RegistroCliente();
        Cliente cliente = rc.buscarPorRut(run);

        runcli = cliente.getRutCliente();
        System.out.println(runcli);
        if (runcli != null) {
            this.jlblNombre.setText(cliente.getNombre() + " " + cliente.getAppaterno() + " " + cliente.getApmaterno());
            this.jlblCategoria.setText("Categoría: " + consultarCategoria(cliente.getCategoria()));
            this.jlblRun.setText("RUN: " + run);
            catCliente = cliente.getCategoria();
            return true;
        } else {
            return false;
        }

    }

    public void descuentoCliente() {
        switch (catCliente) {
            case 1:
                descto = 0.2;
                this.jlblDescuento.setText("20%");
                break;
            case 2:
                descto = 0.1;
                this.jlblDescuento.setText("10%");
                break;

            case 3:
                descto = 0.0;
                this.jlblDescuento.setText("Sin Descuento");
                break;
            default:
                throw new AssertionError();
        }
    }

    public void totalPagar() {
        calculoPago = (int) (precioTicket * descto);
        totalPagar = precioTicket - calculoPago;
        this.jlblTotalPagar.setText("$ " + String.valueOf(totalPagar));
    }

    private String consultarUbicacion(int idUbicacion) {
        String nomUbic;

        RegistroUbicacion rc = new RegistroUbicacion();
        UbicacionEstadio ubicacion = rc.buscarPorId(idUbicacion);
        nomUbic = ubicacion.getNombreUbicacion();
        this.jlblSector.setText(nomUbic);
        return nomUbic;
    }

    private void consultarEstadio(int idEst) {
        String nomEstadio;
        RegistroEstadio res = new RegistroEstadio();
        Estadio estadio = res.buscarPorId(idEst);
        idEstadio = estadio.getIdEstadio();
        nomEstadio = estadio.getNombreEstadio();

        System.out.println(nomEstadio);
        this.jlblEstadio.setText(nomEstadio);
    }

    private String consultarCategoria(int idCategoria) {
        String nomCategoria;

        RegistroCategoria rc = new RegistroCategoria();
        Categoria categoria = rc.buscarPorId(idCategoria);
        nomCategoria = categoria.getNombreCategoria();

        return nomCategoria;
    }

    private int obtenerIdTicket(String runCli, int idEventoTicket) {
        int idTicketComprado;

        RegistroTicket rt = new RegistroTicket();
        Ticket ticket = rt.buscarTicketPorCliente(runCli,idEventoTicket);
        idTicketComprado = ticket.getIdTicket();

        return idTicketComprado;
    }

    private String consultarEquipo(int idVisita) {
        String equipoVisita;
        RegistroEquipo re = new RegistroEquipo();
        Equipo equipo = re.buscarPorId(idVisita);
        equipoVisita = equipo.getNombreEquipo();

        return equipoVisita;
    }

    public void consultarEvento() {
        RegistroEvento regev = new RegistroEvento();
        Evento evento = regev.buscarPorId(idEvento);

        this.jlblEvento.setText(evento.getEquipoLocal() + " vs " + consultarEquipo(evento.getVisita()));
        this.jlblDescripcion.setText(evento.getDescripcionEvento() + " | Jornada: " + evento.getJornadaEvento());
        this.jlblFechaHora.setText(evento.getFechaEvento() + " | " + evento.getHoraEvento() + " hrs");

    }

    public void consultarTicket() {
        RegistroTicket regtic = new RegistroTicket();
        Ticket ticket;
    }

    public void ocultarPago() {
        this.jlblNroTicket.setVisible(false);
        this.jlblPrecioTicket.setVisible(false);
        this.jlblEfectivoTicket.setVisible(false);
        this.jlblDescuentoTicket.setVisible(false);
        this.jlblVueltoTicket.setVisible(false);
    }

    public void mostrarPago() {
        int vuelto;

        System.out.println(efectivo);

        this.jlblNroTicket.setVisible(true);
        this.jlblPrecioTicket.setVisible(true);
        this.jlblEfectivoTicket.setVisible(true);
        this.jlblDescuentoTicket.setVisible(true);
        this.jlblVueltoTicket.setVisible(true);

        this.jlblPrecioTicket.setText("$ " + String.valueOf(precioTicket));
        this.jlblEfectivoTicket.setText("$ " + String.valueOf(efectivo));
        this.jlblDescuentoTicket.setText("$ " + String.valueOf(calculoPago));

        vuelto = efectivo - totalPagar;
        System.out.println(vuelto);
        this.jlblVueltoTicket.setText("$ " + String.valueOf(vuelto));

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblIdEvento = new javax.swing.JLabel();
        jlblRunCliente = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jlblNombre = new javax.swing.JLabel();
        jlblCategoria = new javax.swing.JLabel();
        jlblRun = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlblEvento = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlblDescripcion = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlblFechaHora = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlblEstadio = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlblSector = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlblPrecio = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlblDescuento = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jlblTotalPagar = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jlblPrecioTicket = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jlblDescuentoTicket = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jlblEfectivoTicket = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jlblNroTicket = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jlblVueltoTicket = new javax.swing.JLabel();
        jtxtDinero = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jbtnSalir = new javax.swing.JButton();
        jbtnPagar = new javax.swing.JButton();

        jlblIdEvento.setText("jLabel1");

        jlblRunCliente.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pagar Ticket");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlblNombre.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jlblNombre.setText("jLabel10");

        jlblCategoria.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlblCategoria.setText("jLabel11");

        jlblRun.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlblRun.setText("jLabel11");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoColoColo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblNombre)
                    .addComponent(jlblRun)
                    .addComponent(jlblCategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblCategoria)
                        .addGap(1, 1, 1)
                        .addComponent(jlblRun))))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel1.setText("EVENTO");

        jlblEvento.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlblEvento.setText("jLabel11");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel2.setText("DESCRIPCIÓN");

        jlblDescripcion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlblDescripcion.setText("jLabel11");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel4.setText("FECHA Y HORA");

        jlblFechaHora.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlblFechaHora.setText("jLabel11");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel5.setText("ESTADIO");

        jlblEstadio.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlblEstadio.setText("jLabel11");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel6.setText("SECTOR ESTADIO");

        jlblSector.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlblSector.setText("jLabel11");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel7.setText("PRECIO TICKET");

        jlblPrecio.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlblPrecio.setText("jLabel11");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel8.setText("DESCUENTO");

        jlblDescuento.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlblDescuento.setText("jLabel11");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jlblEvento)
                    .addComponent(jLabel5)
                    .addComponent(jlblEstadio)
                    .addComponent(jLabel7)
                    .addComponent(jlblPrecio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jlblDescripcion))
                        .addGap(180, 180, 180)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jlblFechaHora)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jlblSector))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jlblDescuento))))
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblEvento)
                    .addComponent(jlblDescripcion)
                    .addComponent(jlblFechaHora))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblEstadio)
                    .addComponent(jlblSector))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblPrecio)
                    .addComponent(jlblDescuento))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jLabel9.setText("TOTAL A PAGAR");

        jlblTotalPagar.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jlblTotalPagar.setText("jLabel10");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlblPrecioTicket.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jlblPrecioTicket.setText("PRECIO TICKET");

        jLabel12.setText("PRECIO TICKET");

        jLabel13.setText("DESCUENTO");

        jlblDescuentoTicket.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jlblDescuentoTicket.setText("DESCUENTO");

        jLabel15.setText("EFECTIVO");

        jlblEfectivoTicket.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jlblEfectivoTicket.setText("EFECTIVO");

        jLabel17.setText("NRO TICKET");

        jlblNroTicket.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jlblNroTicket.setText("NRO TICKET");

        jLabel19.setText("VUELTO");

        jlblVueltoTicket.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jlblVueltoTicket.setText("VUELTO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel17)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jlblNroTicket)
                                .addGap(60, 60, 60))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblDescuentoTicket)
                                    .addComponent(jlblPrecioTicket)
                                    .addComponent(jlblEfectivoTicket)
                                    .addComponent(jlblVueltoTicket))
                                .addGap(40, 40, 40))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel17))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlblNroTicket)))
                .addGap(4, 4, 4)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel15)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel19))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jlblPrecioTicket)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblDescuentoTicket)
                        .addGap(10, 10, 10)
                        .addComponent(jlblEfectivoTicket)
                        .addGap(10, 10, 10)
                        .addComponent(jlblVueltoTicket)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtxtDinero.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jtxtDinero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtDineroMouseClicked(evt);
            }
        });
        jtxtDinero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtDineroKeyPressed(evt);
            }
        });

        jLabel10.setText("INGRESE PAGO EFECTIVO");

        jbtnSalir.setBackground(new java.awt.Color(204, 0, 0));
        jbtnSalir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbtnSalir.setText("SALIR");
        jbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirActionPerformed(evt);
            }
        });

        jbtnPagar.setBackground(new java.awt.Color(0, 153, 0));
        jbtnPagar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbtnPagar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnPagar.setText("PAGAR");
        jbtnPagar.setEnabled(false);
        jbtnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9)
                                    .addComponent(jlblTotalPagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtxtDinero)
                                    .addComponent(jSeparator1))
                                .addGap(26, 26, 26)
                                .addComponent(jbtnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblTotalPagar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtDinero, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(jbtnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnPagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed

        if (bandera) {
            this.dispose();
        } else {
            int resp = JOptionPane.showConfirmDialog(this, "¿Desea salir y cancelar la compra?", "Salir de la venta", JOptionPane.YES_NO_OPTION, 3);
            if (resp == 0) {
                this.dispose();
            }
        }


    }//GEN-LAST:event_jbtnSalirActionPerformed

    private void jbtnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPagarActionPerformed

        int idtick;
        try {
            efectivo = Integer.parseInt(this.jtxtDinero.getText());
            if (efectivo < totalPagar) {
                JOptionPane.showMessageDialog(this, "Efectivo Insuficiente", "Alerta", 0);
                this.jtxtDinero.requestFocus();
            } else {
                Ticket ticket = new Ticket(precioTicket, precioTicket, runCliente, null, idEstadio, idUbicacion, idEvento);
                bandera = true;
                RegistroTicket regticket = new RegistroTicket();

                if (regticket.agregar(ticket)) {
                    JOptionPane.showMessageDialog(this, "Pago Realizado Correctamente, gracias por su Compra", "Aviso", 1);

                } else {
                    JOptionPane.showMessageDialog(this, "No se registró el pago", "Aviso", 1);
                }
                this.jlblTotalPagar.setText("");
                this.jtxtDinero.setText("");
                mostrarPago();

                this.jlblNroTicket.setText(String.valueOf(obtenerIdTicket(runCliente,idEvento)));
                this.jtxtDinero.setEnabled(false);
                this.jbtnPagar.setEnabled(false);

            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un monto válido", "Alerta", 1);
            this.jtxtDinero.requestFocus();
        }


    }//GEN-LAST:event_jbtnPagarActionPerformed

    private void jtxtDineroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtDineroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDineroMouseClicked

    private void jtxtDineroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtDineroKeyPressed
        this.jbtnPagar.setEnabled(true);
    }//GEN-LAST:event_jtxtDineroKeyPressed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PagarTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PagarTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PagarTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PagarTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PagarTicket().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbtnPagar;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JLabel jlblCategoria;
    private javax.swing.JLabel jlblDescripcion;
    private javax.swing.JLabel jlblDescuento;
    private javax.swing.JLabel jlblDescuentoTicket;
    private javax.swing.JLabel jlblEfectivoTicket;
    private javax.swing.JLabel jlblEstadio;
    private javax.swing.JLabel jlblEvento;
    private javax.swing.JLabel jlblFechaHora;
    private javax.swing.JLabel jlblIdEvento;
    private javax.swing.JLabel jlblNombre;
    private javax.swing.JLabel jlblNroTicket;
    private javax.swing.JLabel jlblPrecio;
    private javax.swing.JLabel jlblPrecioTicket;
    private javax.swing.JLabel jlblRun;
    private javax.swing.JLabel jlblRunCliente;
    private javax.swing.JLabel jlblSector;
    private javax.swing.JLabel jlblTotalPagar;
    private javax.swing.JLabel jlblVueltoTicket;
    private javax.swing.JTextField jtxtDinero;
    // End of variables declaration//GEN-END:variables
}
